export const robots = [
  {
    "id": 1,
    "first": "Arne",
    "last": "Domenichelli",
    "username": "adomenichelli0",
    "color": "#bd2"
  }, {
    "id": 2,
    "first": "Isa",
    "last": "Beric",
    "username": "iberic1",
    "color": "#d7b"
  }, {
    "id": 3,
    "first": "Wait",
    "last": "Donnell",
    "username": "wdonnell2",
    "color": "#d30"
  }, {
    "id": 4,
    "first": "Annnora",
    "last": "Ben",
    "username": "aben3",
    "color": "#1ec"
  }, {
    "id": 5,
    "first": "Launce",
    "last": "Moulsdale",
    "username": "lmoulsdale4",
    "color": "#56c"
  }, {
    "id": 6,
    "first": "Edward",
    "last": "Feare",
    "username": "efeare5",
    "color": "#e18"
  }, {
    "id": 7,
    "first": "Randee",
    "last": "Kynson",
    "username": "rkynson6",
    "color": "#521"
  }, {
    "id": 8,
    "first": "Robin",
    "last": "Heintz",
    "username": "rheintz7",
    "color": "#0a1"
  }, {
    "id": 9,
    "first": "Jeanie",
    "last": "Sonier",
    "username": "jsonier8",
    "color": "#3a7"
  }, {
    "id": 10,
    "first": "Wilt",
    "last": "Paliser",
    "username": "wpaliser9",
    "color": "#39d"
  }, {
    "id": 11,
    "first": "Aldin",
    "last": "Engall",
    "username": "aengalla",
    "color": "#e7d"
  }, {
    "id": 12,
    "first": "Antoinette",
    "last": "Alekseev",
    "username": "aalekseevb",
    "color": "#a3f"
  }, {
    "id": 13,
    "first": "Nat",
    "last": "Gynn",
    "username": "ngynnc",
    "color": "#5d1"
  }, {
    "id": 14,
    "first": "Leandra",
    "last": "Parlott",
    "username": "lparlottd",
    "color": "#b26"
  }, {
    "id": 15,
    "first": "Alix",
    "last": "Busson",
    "username": "abussone",
    "color": "#332"
  }, {
    "id": 16,
    "first": "Lira",
    "last": "Dorran",
    "username": "ldorranf",
    "color": "#10e"
  }, {
    "id": 17,
    "first": "Eldin",
    "last": "Lupson",
    "username": "elupsong",
    "color": "#6f3"
  }, {
    "id": 18,
    "first": "Wade",
    "last": "Whannel",
    "username": "wwhannelh",
    "color": "#442"
  }, {
    "id": 19,
    "first": "Rollie",
    "last": "Swinley",
    "username": "rswinleyi",
    "color": "#eda"
  }, {
    "id": 20,
    "first": "Marla",
    "last": "Broker",
    "username": "mbrokerj",
    "color": "#5ae"
  }]
